### ISSUE TITLE
64b support for iOS

### ISSUE THREAD

**Issue by shamruk** [MobileAppTracking/air-plugin#7]
Apple has announced:

As we announced in October, beginning February 1, 2015 new iOS apps submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK. Beginning June 1, 2015 app updates will also need to follow the same requirements.

**Comment by harshal-hasoffers** [comment]
Please check the beta branch. It has been updated for Adobe AIR 16.0 beta and supports iOS 64-bit architecture:
https://github.com/MobileAppTracking/air-plugin/tree/beta

**Comment by shamruk** [comment]
Beta branch is the same as master, please check if you have pushed the changes.
Thanks
