### ISSUE TITLE
64bit support for Adobe AIR .ane extension

### ISSUE THREAD

**Issue by Mintonist** [MobileAppTracking/air-plugin#8]
Hi

According to https://developer.apple.com/news/?id=10202014a all ios application and anes must have 64-bit iOS compatibility since 1 feb 2015 . Adobe supports it in AIR 16 SDK. Do you have plans to rebuild your extension?
 
Error message while packaging .ipa file:
Error: libMobileTracking.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

Thx

**Comment by plaidtopia** [comment]
I, too, am very interested in this. Any update here?

**Comment by john-gu** [comment]
Hi all, we're testing the 16.0 build for release later this week. In the meantime you may try using the ANEs from the "beta" branch that we used 16.0 beta to build.

**Comment by john-gu** [comment]
Please try the latest ANE release which has 64-bit iOS compatibility.
